#!/usr/bin/env python3


from http.server import HTTPServer, BaseHTTPRequestHandler


ENCODING = "UTF-8"

TESTHTML = """
<html>
<head>
<title>Test Page</title>
</head>
<body>
<h1>Test Page</h1>
This is a test page.



</body>
</html>
"""





class ReqHandler(BaseHTTPRequestHandler):
    
    def __init__(self,request, client_address, server):
        super().__init__(request, client_address, server)
        #print(super().__doc__)
        print(self.__doc__)
        pass

    def do_GET(self):
        WebServer.count += 1
        
        self.send_response(200)
        self.end_headers()
        
        #self.wfile.write(bytes("Count: "+str(WebServer.count),encoding=ENCODING))
        self.wfile.write(bytes(TESTHTML,encoding=ENCODING))

class WebServer:
    
    
    count = 0
    def __init__(self,port=8080,hostname=''):
        self.port = port
        self.hostname = hostname
        
    
    
    def run(self,server_class=HTTPServer, handler_class=ReqHandler):
        server_address = (self.hostname, self.port)
        
        print(f"Listening on {server_address}...")
        httpd = server_class(server_address, handler_class)
        httpd.serve_forever()


def test1():
    r = ReqHandler()


def main():
    w = WebServer()
    w.run()

if __name__ == '__main__':
    main()
    #test1()